name: decision
channels:
  - defaults
  - conda-forge
  - tofuproject
dependencies:
  - attrs
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - coverage
  - cryptography
  - idna
  - iniconfig
  - libcxx
  - libffi
  - libsqlite
  - libzlib
  - more-itertools
  - ncurses
  - openssl
  - packaging
  - pip
  - pluggy
  - py
  - pycparser
  - pyopenssl
  - pysocks
  - pytest
  - pytest-cov
  - python
  - python_abi
  - readline
  - requests
  - setuptools
  - sqlite
  - tk
  - toml
  - tomli
  - tzdata
  - urllib3
  - wheel
  - xz
  - zlib
  - pip:
      - blinker
      - click
      - chardet
      - dash
      - dash-bootstrap-components
      - dash-core-components
      - dash-daq
      - dash-html-components
      - dash-table
      - flask
      - importlib-metadata
      - itsdangerous
      - jinja2
      - joblib
      - kaleido
      - kneed
      - markupsafe
      - numpy
      - pandas
      - pdfkit
      - plotly
      - psutil
      - python-dateutil
      - pytz
      - pyyaml
      - scikit-learn
      - scipy
      - shapely
      - six
      - tenacity
      - threadpoolctl
      - werkzeug
      - zipp
      - selenium
      - multiprocess
      - dash[testing]
