name: decision

channels:
  - conda-forge
  - defaults

dependencies:
  - ca-certificates
  - certifi
  - libcxx
  - libffi
  - python-kaleido
  - ncurses
  - openssl
  - pip
  - python==3.9.16
  - pytest==6.2.4
  - pytest-cov==2.10.1
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
      - boto3==1.28.51
      - click==8.1.3
      - dash==2.8.1
      - dash-bootstrap-components==1.4.0
      - dash-core-components==2.0.0
      - dash-extensions==0.0.41
      - dash-daq==0.5.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - flask
      - importlib-metadata
      - itsdangerous
      - jinja2==3.1.2
      - kneed==0.8.2
      - markupsafe
      - numpy==1.24.2
      - pandas==1.5.3
      - plotly==5.13.1
      - pdfkit
      - psutil
      - python-dateutil
      - pytz
      - PyYAML
      - six
      - scikit-learn==1.2.2
      - tenacity
      - werkzeug
      - zipp
